language: cpp
matrix:
  include:
    - os: linux
      script:
        - sudo add-apt-repository ppa:alexlarsson/flatpak
        - sudo apt update
        - sudo apt install flatpak flatpak-builder
        - sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        - sudo flatpak install -y flathub org.gnome.Platform/x86_64/3.26
        - sudo flatpak install -y flathub org.gnome.Platform.Locale/x86_64/3.26
        - sudo flatpak install -y flathub org.gnome.Sdk/x86_64/3.26
        - sudo flatpak install -y flathub org.gnome.Sdk.Locale/x86_64/3.26
        - mkdir -p .cache
        - "tar --xattrs --xattrs-include=* -xf .cache/cache.tar || true"
        - flatpak-builder --repo=repo ./build org.sorn.KiCad.yml
        - flatpak build-bundle repo kicad.flatpak org.sorn.KiCad
      before_cache:
        - tar --xattrs --xattrs-include=* -cpf .cache/cache.tar install/linux/.flatpak-builder/
      cache:
        directories:
          - .cache
