language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services:
        - docker
      script:
        - mkdir -p .cache
        - "tar --xattrs --xattrs-include=* -xf .cache/cache.tar || true"
        - docker run --privileged -v$PWD:/w -it ubuntu:18.04 /bin/bash -c "cd /w/ci && ./flatpak.sh"
      before_cache:
        - tar --xattrs --xattrs-include=* -cpf .cache/cache.tar install/linux/.flatpak-builder/
      cache:
        directories:
          - .cache
